# Generated by Django 4.2 on 2024-05-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=2, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
