# Generated by Django 4.2 on 2024-05-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options_post_hide_from_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Скрыт'),
        ),
    ]
